### ISSUE TITLE
Error in air-gapped environments

### ISSUE THREAD

**Issue by making** [bosh-elastic-stack/curator-boshrelease#1]
```
Error: Action Failed get_task: Task dbeba010-53a9-4179-5c44-f5ec80ba5abe result: Compiling package curator: Running packaging script: Running packaging script: Command exited with 1; Stdout: Collecting elasticsearch!=6.0.0,<7.0.0,>=5.5.2 (from elasticsearch-curator)
Collecting boto3>=1.7.24 (from elasticsearch-curator)
Collecting requests_aws4auth>=0.9 (from elasticsearch-curator)
Collecting click>=6.7 (from elasticsearch-curator)
Collecting pyyaml>=3.10 (from elasticsearch-curator)
Collecting voluptuous>=0.9.3 (from elasticsearch-curator)
Collecting certifi>=2018.4.16 (from elasticsearch-curator)
Collecting six>=1.11.0 (from elasticsearch-curator)
Collecting urllib3>=1.21.1 (from elasticsearch!=6.0.0,<7.0.0,>=5.5.2->elasticsearch-curator)
Collecting botocore<1.13.0,>=1.12.39 (from boto3>=1.7.24->elasticsearch-curator)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.7.24->elasticsearch-curator)
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3>=1.7.24->elasticsearch-curator)
Collecting requests (from requests_aws4auth>=0.9->elasticsearch-curator)
Collecting docutils>=0.10 (from botocore<1.13.0,>=1.12.39->boto3>=1.7.24->elasticsearch-curator)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.13.0,>=1.12.39->boto3>=1.7.24->elasticsearch-curator)
   Complete output from command python setup.py egg_info:
   Download error on https://pypi.python.org/simple/setuptools_scm/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
   Download error on https://pypi.python.org/simple/setuptools-scm/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
   Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
   Download error on https://pypi.python.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
   No local packages or working download links found for setuptools_scm
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/var/vcap/data/tmp/pip-build-m34xt8lt/python-dateutil/setup.py", line 86, in <module>
       "test": Unsupported
     File "/var/vcap/packages/python3/lib/python3.5/distutils/core.py", line 108, in setup
       _setup_distribution = dist = klass(attrs)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
       self.fetch_build_eggs(attrs['setup_requires'])
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
       replace_conflicting=True,
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
       dist = best[req.key] = env.best_match(req, ws, installer)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
       return self.obtain(req, installer)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
       return installer(requirement)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
       return cmd.easy_install(req)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
       raise DistutilsError(msg)
   distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')

   ----------------------------------------
, Stderr: + export PATH=/var/vcap/packages/python3/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ PATH=/var/vcap/packages/python3/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin

+ export LD_LIBRARY_PATH=/var/vcap/packages/python3/lib:
+ LD_LIBRARY_PATH=/var/vcap/packages/python3/lib:
+ export C_INCLUDE_PATH=/var/vcap/packages/python3/include:
+ C_INCLUDE_PATH=/var/vcap/packages/python3/include:
+ pip3 install --no-index --find-links ./curator/ --prefix=/var/vcap/packages/curator elasticsearch-curator
Command "python setup.py egg_info" failed with error code 1 in /var/vcap/data/tmp/pip-build-m34xt8lt/python-dateutil/

Task 1404404 | 09:17:21 | Error: Action Failed get_task: Task dbeba010-53a9-4179-5c44-f5ec80ba5abe result: Compiling package curator: Running packaging script: Running packaging script: Command exited with 1; Stdout: Collecting elasticsearch!=6.0.0,<7.0.0,>=5.5.2 (from elasticsearch-curator)
Collecting boto3>=1.7.24 (from elasticsearch-curator)
Collecting requests_aws4auth>=0.9 (from elasticsearch-curator)
Collecting click>=6.7 (from elasticsearch-curator)
Collecting pyyaml>=3.10 (from elasticsearch-curator)
Collecting voluptuous>=0.9.3 (from elasticsearch-curator)
Collecting certifi>=2018.4.16 (from elasticsearch-curator)
Collecting six>=1.11.0 (from elasticsearch-curator)
Collecting urllib3>=1.21.1 (from elasticsearch!=6.0.0,<7.0.0,>=5.5.2->elasticsearch-curator)
Collecting botocore<1.13.0,>=1.12.39 (from boto3>=1.7.24->elasticsearch-curator)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.7.24->elasticsearch-curator)
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3>=1.7.24->elasticsearch-curator)
Collecting requests (from requests_aws4auth>=0.9->elasticsearch-curator)
Collecting docutils>=0.10 (from botocore<1.13.0,>=1.12.39->boto3>=1.7.24->elasticsearch-curator)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.13.0,>=1.12.39->boto3>=1.7.24->elasticsearch-curator)
   Complete output from command python setup.py egg_info:
   Download error on https://pypi.python.org/simple/setuptools_scm/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
   Download error on https://pypi.python.org/simple/setuptools-scm/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
   Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
   Download error on https://pypi.python.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
   No local packages or working download links found for setuptools_scm
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "/var/vcap/data/tmp/pip-build-m34xt8lt/python-dateutil/setup.py", line 86, in <module>
       "test": Unsupported
     File "/var/vcap/packages/python3/lib/python3.5/distutils/core.py", line 108, in setup
       _setup_distribution = dist = klass(attrs)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
       self.fetch_build_eggs(attrs['setup_requires'])
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
       replace_conflicting=True,
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
       dist = best[req.key] = env.best_match(req, ws, installer)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
       return self.obtain(req, installer)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
       return installer(requirement)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
       return cmd.easy_install(req)
     File "/var/vcap/packages/python3/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
raise DistutilsError(msg)
   distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')

   ----------------------------------------
, Stderr: + export PATH=/var/vcap/packages/python3/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ PATH=/var/vcap/packages/python3/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ export LD_LIBRARY_PATH=/var/vcap/packages/python3/lib:
+ LD_LIBRARY_PATH=/var/vcap/packages/python3/lib:
+ export C_INCLUDE_PATH=/var/vcap/packages/python3/include:
+ C_INCLUDE_PATH=/var/vcap/packages/python3/include:
+ pip3 install --no-index --find-links ./curator/ --prefix=/var/vcap/packages/curator elasticsearch-curator
Command "python setup.py egg_info" failed with error code 1 in /var/vcap/data/tmp/pip-build-m34xt8lt/python-dateutil/
```

**Comment by making** [comment]
already fixed
